name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: CI-Build
        run: MINGW_INSTALLS=${{ matrix.msystem }} ./ci-build.sh

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}-packages
          path: artifacts/*.pkg.tar.*

      - name: "Upload sources"
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: artifacts/*.src.tar.*
